### PR TITLE
Add v2.0.5 signatures for hello

### PR DESCRIPTION
**Pull request by garethtdavies**

### CODE REVIEW

**Comment by ianamunoz** [comment]
@garethtdavies What version of debian is your VM? Mine is:
```
vagrant@zcash-build:~/gitian.sigs$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```
I think that may be causing the difference in the `zcash-2.0.5-linux64.tar.gz` which should match.

**Comment by garethtdavies** [comment]
@ianamunoz 9.8 I am seeing there is an upgrade available to 9.9 so I'll update and rerun this.

```
==> zcash-build: Checking if box 'debian/stretch64' version '9.8.0' is up to date...
==> zcash-build: A newer version of the box 'debian/stretch64' for provider 'virtualbox' is
==> zcash-build: available! You currently have version '9.8.0'. The latest is version
==> zcash-build: '9.9.0'. Run `vagrant box update` to update.
```

**Comment by ianamunoz** [comment]
Yeah no problem. That's what I figured b/c i saw the upgrade go in. I will re-run another as well. 👍

**Comment by garethtdavies** [comment]
Forced pushed running on 9.9 but looks the same. Presumably, that's expected as the VM version shouldn't have any effect on the container where the magic is happening? I'll take a look at a diff between our outputs to try and narrow down. For reference I am also running on current master #90482ef12fba71b623d32028fdf769d60b15259a on zcash-gitian.

```
vagrant@zcash-build:~/gitian.sigs$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```

**Comment by garethtdavies** [comment]
So it's just these two lines 😕 

```
    3d3ff07e86de6447a69a9387ba3ac605c660c1df239e4207d3a69aefb02127bc  zcash-2.0.5-linux64-debug.tar.gz | ca03322fb7972455825c72acb52d3b5758df33e597cafd950baddda764fe8d51  zcash-2.0.5-linux64-debug.tar.gz
    1d8ce8942c197587dafac6cfc89f41772bda3ac7865aca1c0eac864f7a200955  zcash-2.0.5-linux64.tar.gz | dd5acf02f71385c43eefadaa97668de9b10aaf6051b31134e5188d5551e4c383  zcash-2.0.5-linux64.tar.gz
```

**Comment by garethtdavies** [comment]
I completed a third build and force pushed. Ensured that the VM was destroyed before starting, and I was on the current master of zcash-gitian with the latest vagrant box available. Still the same output for me.

Happy to try anything if other ideas.

**Comment by ianamunoz** [comment]
I think your are correct and i have somehow introduced a mutability. Will try and reproduce your sigs as @charlieok  had your same hashes. We are adding a hot fix so we will re-run in the morning.

**Pull request closed without merging**
